// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:64523532480:web:d68548472442d856c4d525',
    messagingSenderId: '64523532480',
    projectId: 'emage13-b1909',
    authDomain: 'emage13-b1909.firebaseapp.com',
    storageBucket: 'emage13-b1909.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:64523532480:android:f1b060e9d741d882c4d525',
    messagingSenderId: '64523532480',
    projectId: 'emage13-b1909',
    storageBucket: 'emage13-b1909.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:64523532480:ios:f8600dc2968d95a4c4d525',
    messagingSenderId: '64523532480',
    projectId: 'emage13-b1909',
    storageBucket: 'emage13-b1909.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
    appId: '1:64523532480:ios:f8600dc2968d95a4c4d525',
    messagingSenderId: '64523532480',
    projectId: 'emage13-b1909',
    storageBucket: 'emage13-b1909.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
    appId: '1:64523532480:web:080e7d8e9d7d67fec4d525',
    messagingSenderId: '64523532480',
    projectId: 'emage13-b1909',
    authDomain: 'emage13-b1909.firebaseapp.com',
    storageBucket: 'emage13-b1909.firebasestorage.app',
  );
}
